stardis_config_version: 1.0
atom_data: kurucz_cd23_chianti_H_He.h5
input_model:
    type: marcs
    fname: ../quickstart/sun.mod
    final_atomic_number: 30
opacity:
    file: {}
    bf:
        H_I: {}
    ff:
        H_I: {}
    disable_electron_scattering: False
    line:
        disable: False
        broadening: [radiation, linear_stark, quadratic_stark, van_der_waals]
no_of_thetas: 10
