stardis_config_version: 1.0
atom_data: kurucz_cd23_chianti_H_He.h5
model:
    type: marcs
    fname: sun.mod
    final_atomic_number: 30
opacity:
    file:
        Hminus_bf: h_minus_cross_section_wbr.dat
    bf:
        H_I: {}
    ff:
        H_I: {}
    disable_electron_scattering: False
    line:
        disable: False
        broadening: [radiation, linear_stark, quadratic_stark, van_der_waals]
        min: 6500 AA
        max: 6600 AA
no_of_thetas: 20